### ISSUE TITLE
Enhancement Request: Add Selector for First Four Articles and Support for Cover/Images in Paragraphs

### ISSUE THREAD

**Issue by Monkfishare** [cheeberger/Economist2Epub#2]
1. add selector for including the first four articles
`section.layout-weekly-edition-section>div>ul>li>a`
2. add cover and the image in paragraphs

**Comment by cheeberger** [comment]
1. Ahh must have missed those. Should be an easy fix.
2. Not sure what you mean by this. Magazine cover maybe?
